import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Inicio - Crud",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="https://clinicalascondesservicedesk.attachments.freshservice.com/data/helpdesk/attachments/production/24001888736/fav_icon/LOGO_CLC.PNG?Expires=1730891830&Signature=HMDpi1NjjUBoyAZCA0YccxUs2hQxoufep517RAE4-vpZ2nsD4AZU4nH5pqHOuYov753s-3q7NyZI1cGUHjR2ziAnwpDZ8ITQTQiGotkQNInEufVTOcpE9ySVU8WulgBfKc3p5jgoF8ngqlsCEtNXalR-UFgBJstyB1v1vwIujSvQdRSg5NmQOvSKKSlnLD1ws2iJCnHlLpRoP8kFBvTaOzqDxAhFvkFESj3aoC5qXuEeknr~GEIo0vUsZ64ZGUfe8sYfY7VUYeX7n7Tg5~t9npOBwffQjDBQpCeEYlBa72SCBeMNcvLDZunPfo20Cywb0h~IyDQhjiv6mWthCVswwg__&Key-Pair-Id=APKAIPHBXWY2KT5RCMPQ" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100 dark:bg-gray-900 dark:text-white transition-colors duration-300`}
      >
        {children}
      </body>
    </html>
  );
}